# Generated by Django 4.1.7 on 2023-04-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdopcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
