# Generated by Django 4.1.7 on 2023-04-19 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdopcion', '0002_alter_mascota_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-fechaComent']},
        ),
        migrations.AddField(
            model_name='comentario',
            name='fechaComent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
